version: '3.8'
services:
  web:
    build: .gradle
    image: basic-forum
  mysql:
    image: mysql:8.0
    container_name: mysql2
    restart: always
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: mini4
      MYSQL_USER: mini4
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: root

  redis:
    image: redis
    container_name: redis2
    ports:
      - "6379:6379"
    extra_hosts:
      - "host.docker.internal:host-gateway"

