version: '3.8'
services:
  web:
    container_name: basic-community-forum-web-1
    image: basic-forum
    depends_on:
      - mysql
      - redis
    ports:
      - "8080:8080"

  mysql:
    image: mysql:8.0
    container_name: mysql2
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: mini4
      MYSQL_USER: mini4
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis
    container_name: redis2
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mysql_data:  # MySQL 데이터 저장을 위한 볼륨
  redis_data:  # Redis 데이터 저장을 위한 볼륨