services:
  web:
    container_name: basic-forum-web
    image: colline/basic-forum
    depends_on:
      - mysql
      - redis
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mysql:
    image: mysql:8.0
    container_name: mysql2
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: mini4
      MYSQL_USER: mini4
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    extra_hosts:
      - "host.docker.internal:host-gateway"

  redis:
    image: redis
    container_name: redis2
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  mysql_data:  # MySQL 데이터 저장을 위한 볼륨
  redis_data:  # Redis 데이터 저장을 위한 볼륨